/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/translation/{lang}": {
    /** Get all achievements */
    get: operations["BasicController_getBaseTranslations"];
  };
  "/achievements/{lang}": {
    /** Get all achievements */
    get: operations["HandbookController_getAchievements"];
  };
  "/aspiration-groups/{lang}": {
    /** Get all achievements */
    get: operations["HandbookController_getAspirationGroups"];
  };
  "/aspirations/{lang}": {
    /** Get all achievements */
    get: operations["HandbookController_getAspirations"];
  };
  "/skills/{lang}": {
    /** Get all achievements */
    get: operations["HandbookController_getSkills"];
  };
  "/trait-groups/{lang}": {
    /** Get all achievements */
    get: operations["HandbookController_getTraitGroups"];
  };
  "/traits/{lang}": {
    /** Get all achievements */
    get: operations["HandbookController_getTraits"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    PagesBasicTranslationDto: {
      error: string;
      profile: string;
      login: string;
      logout: string;
      signup: string;
      settings: string;
      trees: string;
      challenges: string;
      randomizer: string;
      handbook: string;
      worlds: string;
      tracker: string;
    };
    UtilityBasicTranslationDto: {
      open: string;
      close: string;
      save: string;
      cancel: string;
      continue: string;
      complete: string;
      reset: string;
      back: string;
      exit: string;
      create: string;
      edit: string;
      delete: string;
    };
    SettingsBasicTranslationDto: {
      username: string;
      password: string;
    };
    BasicTranslationNoLangDto: {
      pages: components["schemas"]["PagesBasicTranslationDto"];
      utility: components["schemas"]["UtilityBasicTranslationDto"];
      settings: components["schemas"]["SettingsBasicTranslationDto"];
    };
    BasicTranslationDto: {
      data: components["schemas"]["BasicTranslationNoLangDto"];
    };
    TranslationWithDescriptionDto: {
      name: string;
      description: string;
    };
    AchievementsDto: {
      data: {
        [key: string]: components["schemas"]["TranslationWithDescriptionDto"];
      };
    };
    AspirationGroupsDto: {
      data: {
        [key: string]: string;
      };
    };
    AspirationStepDto: {
      label: string;
      tasks: string[];
    };
    AspirationItemDto: {
      name: string;
      description: string;
      data: {
        [key: string]: components["schemas"]["AspirationStepDto"];
      };
    };
    AspirationsDto: {
      data: {
        [key: string]: components["schemas"]["AspirationItemDto"];
      };
    };
    SkillsDto: {
      data: {
        [key: string]: components["schemas"]["TranslationWithDescriptionDto"];
      };
    };
    TraitGroupsDto: {
      data: {
        [key: string]: string;
      };
    };
    TraitsDto: {
      data: {
        [key: string]: components["schemas"]["TranslationWithDescriptionDto"];
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get all achievements */
  BasicController_getBaseTranslations: {
    parameters: {
      path: {
        /** @description Language */
        lang: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["BasicTranslationDto"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /** Get all achievements */
  HandbookController_getAchievements: {
    parameters: {
      path: {
        /** @description Language */
        lang: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["AchievementsDto"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /** Get all achievements */
  HandbookController_getAspirationGroups: {
    parameters: {
      path: {
        /** @description Language */
        lang: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["AspirationGroupsDto"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /** Get all achievements */
  HandbookController_getAspirations: {
    parameters: {
      path: {
        /** @description Language */
        lang: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["AspirationsDto"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /** Get all achievements */
  HandbookController_getSkills: {
    parameters: {
      path: {
        /** @description Language */
        lang: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["SkillsDto"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /** Get all achievements */
  HandbookController_getTraitGroups: {
    parameters: {
      path: {
        /** @description Language */
        lang: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["TraitGroupsDto"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
  /** Get all achievements */
  HandbookController_getTraits: {
    parameters: {
      path: {
        /** @description Language */
        lang: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["TraitsDto"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Not found */
      404: {
        content: never;
      };
    };
  };
}
