import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import AddCircleOutlineIcon from '@mui/icons-material/AddCircleOutline';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import BedtimeIcon from '@mui/icons-material/Bedtime';
import BedtimeOffIcon from '@mui/icons-material/BedtimeOff';
import BuildIcon from '@mui/icons-material/Build';
import CakeIcon from '@mui/icons-material/Cake';
import CropOriginalIcon from '@mui/icons-material/CropOriginal';
import DoneIcon from '@mui/icons-material/Done';
import MenuBookIcon from '@mui/icons-material/MenuBook';
import CasinoIcon from '@mui/icons-material/Casino';
import Crop169OutlinedIcon from '@mui/icons-material/Crop169Outlined';
import ViewStreamIcon from '@mui/icons-material/ViewStream';

export const Profile = AccountCircleIcon;
export const Plus = AddCircleOutlineIcon;
export const Sparcles = AutoAwesomeIcon;
export const Moon = BedtimeIcon;
export const MoonStriked = BedtimeOffIcon;
export const Settings = BuildIcon;
export const Cake = CakeIcon;
export const Image = CropOriginalIcon;
export const Check = DoneIcon;
export const Book = MenuBookIcon;
export const Dice = CasinoIcon;
export const Point = Crop169OutlinedIcon;
export const TwoPoints = ViewStreamIcon;
