export enum CAREERS {
  Actor = "Актер",
  Detective = "Детектив",
  Doctor = "Доктор",
  InteriorDecorator = "Дизайнер интерьеров",
  Scientist = "Ученый",

  CivilDesigner = "Строительный инженер",
  Conservatorist = "Эколог",
  Critic = "Критик",
  Education = "Преподаватель",
  Engineering = "Инженер",
  Gardener = "Садовод",
  Law = "Юрист",
  Military = "Военный служащий",
  Politician = "Политик",
  Salaryperson = "Сарариман",
  SocialMedia = "Социальные сети",
  StyleInfluencer = "Законодатель стиля",

  Astronaut = "Космонавт",
  Athlete = "Спортсмен",
  Business = "Бизнес",
  Criminal = "Преступник",
  Culinary = "Кулинар",
  Entertainer = "Исполнитель",
  Painter = "Художник",
  SecretAgent = "Тайный агент",
  TechGuru = "Технический специалист",
  Writer = "Писатель",

  Babysitter = "Няня",
  Barista = "Бармен",
  Diver = "Водолаз",
  FastFoodEmployee = "Официант",
  Fisherman = "Рыболов",
  Lifeguard = "Спасатель",
  ManualLaborer = "Разнорабочий",
  RetailEmployee = "Продавец",
  Simfluencer = "Симфлюэнсер",
  VideoGameStreamer = "Игровой стример",
  DramaClub = "Драмкружок",
  SoccerTeamPlayer = "Игрок футбольной команды",
  FootballTeamMember = "Игрок футбольной команды",
  Scouting = "Скаут",
  CheerTeamMember = "Участник группы поддержки",
  ESportsCompetitor = "Участник соревнований по киберспорту",
  ComputerTeamMember = "Член компьютерного клуба",
  ChessTeamMember = "Член шахматного клуба",
  FreelanceWriter = "Внештатный корреспондент",
  FreelanceProgrammer = "Внештатный программист",
  FreelanceCrafter = "Внештатный производитель",
  FreelancePainter = "Графический дизайнер",
  FashionPhotographer = "Модный фотограф",
  ParanormalInvestigator = "Паранормальный сыщик",
}
